name: UltimateUserInterface
version: '${version}'
main: self.starvern.ultimateuserinterface.UUIPlugin
api-version: "1.21"
authors:
  - Starvern
description: An advanced GUI management system for ease-of-use.
dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false
      join-classpath: true
    HeadDatabase:
      load: BEFORE
      required: false
      join-classpath: true
    Nexo:
      load: BEFORE
      required: false
      join-classpath: true
commands:
  interface:
    description: Open a gui
    permission: uui.command.interface
    aliases: [if]
    permission-message: "Insufficient permissions."
    usage: interface <gui_name | reload>
permissions:
  uui.command.interface:
    description: Allows the user to use /interface
    default: op
  uui.command.interface.reload:
    description: Allows the user to use /interface reload
    default: op